"""Add displayname field

Revision ID: b087d7626953
Revises: 387599bc2a22
Create Date: 2022-03-16 18:12:15.355339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b087d7626953'
down_revision = '387599bc2a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('displayname', sa.String(), server_default='user341324', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'displayname')
    # ### end Alembic commands ###
