"""Remove the titles from posts

Revision ID: b2bd63206105
Revises: 7ff9d5c657cb
Create Date: 2022-03-24 17:50:58.721952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2bd63206105'
down_revision = '7ff9d5c657cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
